seed: 7113064149
batch_size: 32
num_workers: 4
epochs: 1500
dataset_file: SHHA
data_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\train_data'
val_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\train_data\images'
test_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\test_data'
mode: 'points'                 # 'density' | 'points' | 'class'
crop_size:  [256, 256]
crop_type: 'center'
gray: False
device: cuda
out_dir: 'D:\output\FOCAL_AND_PATCH'
#---------------------------MODEL-----------------------------------------------------
in_ch: 3  # 1=灰階, 3=RGB
fpn_c: 128
cond_c: 64
t_dim: 256
with_score: True
lr: 1e-4
lr_backbone: 1e-5
diffusion_T: 1000
K: 5
signal_scale: 2.0
loss_mode: str = "x0_count",  # "eps" 或 "x0_count"
lambda_exist: 50.0
lambda_eps: 1.0  # 只在 eps 模式用
lambda_x0: 50.0  # 只在 x0_count 模式用
lambda_cnt:  1.0  # 只在 x0_count 模式用
log_every:  50
max_norm:  1.0
