seed: 7113064149
batch_size: 32
epochs: 1500
dataset_file: SHHA
data_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\train_data'
val_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\train_data\images'
test_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\test_data'
mode: 'points'                 # 'density' | 'points' | 'class'
crop_size:  [256, 256]
crop_type: 'center'
gray: False
device: cuda
out_dir: 'C:\pycharm\pointdiff_new\output_add_align_corners=True'
#---------------------------MODEL-----------------------------------------------------
in_ch: 3  # 1=灰階, 3=RGB
fpn_c: 128
cond_c: 64
t_dim: 256
with_score: True
lr: 1e-4
lr_backbone: 1e-5
diffusion_T: 1000
signal_scale: 2.0
